### ISSUE TITLE
What do I do with the IP address

### ISSUE THREAD

**Issue by s12227054** [Nomagno/NDS-NetworkedInput#3]
What do I put in under ip address? I tried my wifi network's ip address and it didn't do anything.

**Comment by Nomagno** [comment]
On the 3DS/DS client side, you have to introduce your PC's IP address. You can find out: 

- On Android by going into device info/wifi settings and looking everwhere for an IP that USUALLY looks like 192.168.XXX.XXX
- On Linux and MacOS by typing `ifconfig` and looking for a similar looking IP
- On Windows by opening a command prompt, typing `ipconfig` and looking for a similar looking IP

Then introduce it on your console. MAKE SURE YOUR CONSOLE AND YOUR DEVICE ARE ON THE SAME NETWORK.

Best regards.

**Comment by s12227054** [comment]
> On the 3DS/DS client side, you have to introduce your PC/Phone's Local IPv4 address. You can find out: 
> 
> - On Android by going into device info/wifi settings and looking everwhere for an IP that USUALLY looks like 192.168.XXX.XXX
> - On Linux and MacOS by typing `ifconfig` into the terminal and looking for a similar looking IP
> - On Windows by opening a command prompt, typing `ipconfig` and looking for a similar looking IP
> 
> Then introduce it on your console. MAKE SURE YOUR CONSOLE AND YOUR DEVICE ARE ON THE SAME NETWORK.
> 
> Best regards.

I did everything, my phone isn't reporting any input

**Comment by Nomagno** [comment]
Please make sure you are connected to the same network and you are inputting your phone's IP Address correctly. For reference, when it does report input it should look like this:
![Screenshot_20210704-120433_1](https://user-images.githubusercontent.com/62209334/124380964-41c20d00-dcc0-11eb-8acc-97150d306180.png)

**Comment by Nomagno** [comment]
Also since this issue seems to be uncommon, please test with the old Louvish Console releases as well as my new ones.

**Comment by s12227054** [comment]
> Also since this issue seems to be uncommon, please test with the old Louvish Console releases as well as my new ones.
> NOTE: THE SERVER WILL NOT REPORT ANY INPUT UNLESS YOU'VE SELECTED THE UDP KEYBOARD AND RESTARTED THE APP

Even when I select the udp keyboard, it doesn't register. Is the ip address the one shown here?![Screenshot_20210704-062118_Settings.jpg](https://user-images.githubusercontent.com/29942566/124381370-158e9800-dc90-11eb-8cbf-2490acbecefa.jpg)

**Comment by Nomagno** [comment]
Yes, yes it is. I'm afraid this is either an issue with the Android app (Which I unfortunately cannot fix) or with your router/phone firewall configuration, which is something I cannot help with.

**Comment by s12227054** [comment]
> Yes, yes it is. I'm afraid this is either an issue with the Android app (Which I unfortunately cannot fix) or with your router/phone firewall configuration, which is something I cannot help with.

Do I need to port forward?

**Comment by Nomagno** [comment]
> Do I need to port forward?
You need to port forward at the local level, which is usually done in the DEVICE firewall, not the router. You should not need to touch the router, but if you happen to have any kind of firewall on your Android install or special router config that prohibits this behaviour (Unlikely) please forward UDP port 3210.

**Comment by s12227054** [comment]
> > Do I need to port forward?
> 
> You need to port forward at the local level, which is usually done in the DEVICE firewall, not the router. You should not need to touch the router, but if you happen to have any kind of firewall on your Android install or special router config that prohibits this behaviour (Unlikely) please forward UDP port 3210.
> 

I get a new error, inet_aton() failed

**Comment by Nomagno** [comment]
Unfortunately I have just the Android server deemed unmaintainable, the fact it doesn't work properly on modern phones is simply out of my control. Sorry, I am trying to make a modern implementation with a better architecture. Best regards!
